# 指定服务名和端口
spring:
  application:
    name: turbine
server:
  port: 7001
# 注册到注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

# 指定收集路径
turbine:
  instanceUrlSuffix: /hystrix.stream
# 指定了需要收集监控信息的服务名，多个以“,”进行区分
  app-config: hystrix-consumer
# 指定集群名称,若为default则为默认集群，多个集群则通过此配置区分
  clusterNameExpression: new String("default")
# 此配置默认为false，则服务是以host进行区分，若设置为true则以host+port进行区分
  aggregator:
    cluster-config: default
  combine-host-port: true
