# \u914D\u7F6E\u670D\u52A1\u7AEF\u53E3\u548C\u540D\u79F0
spring:
  application:
    name: eureka-client
server:
  port: 2001
#  port: 2002

# \u5C06\u670D\u52A1\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

