# 配置服务名称及端口
spring:
  application:
    name: eureka-client
server:
  port: 2001
#  port: 2002

# 将服务注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
#——————————————添加健康检查配置——————————————
  instance:
# 该配置指示eureka客户端需要向eureka服务器发送心跳的频率  (Spring Cloud默认该配置是 30s)
    lease-renewal-interval-in-seconds: 1
# 该配置指示eureka服务器在接收到最后一个心跳之后等待的时间，然后才能从列表中删除此实例 (Spring Cloud默认该配置是 90s)
    lease-expiration-duration-in-seconds: 10