#\u914D\u7F6E\u670D\u52A1\u53CA\u7AEF\u53E3
spring:
  application:
    name: fegin-consumer
server:
  port: 4001
# \u5C06\u670D\u52A1\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/