# 配置服务及端口
spring:
  application:
    name: fegin-consumer
server:
  port: 4001
# 注册到注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
# 从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
    registry-fetch-interval-seconds: 5