#配置服务名称及端口
spring:
  application:
    name: hystrix-consumer
server:
  port: 5001
# 服务注册中心实例的主机名
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/


hystrix:
  command:
    default:
      circuitBreaker:
# 从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
        requestVolumeThreshold: 5
# 错误百分比下限
        errorThresholdPercentage: 60
      execution:
        isolation:
          thread:
# 设置超时时间
            timeoutInMilliseconds: 3000


# 更多配置参考https://blog.csdn.net/harris135/article/details/77879148?locationNum=3&fps=1