spring:
  application:
    name: hystrix-consumer
server:
  port: 5001
# \u5C06\u670D\u52A1\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/


hystrix:
  command:
    default:
      circuitBreaker:
# \u8BBE\u7F6E\u8BF7\u6C42\u603B\u6570\u4E0B\u9650
        requestVolumeThreshold: 5
# \u9519\u8BEF\u767E\u5206\u6BD4\u4E0B\u9650
        errorThresholdPercentage: 60
      execution:
        isolation:
          thread:
# \u8BBE\u7F6E\u8D85\u65F6\u65F6
            timeoutInMilliseconds: 3000


#\u66F4\u591A\u914D\u7F6E\u53C2\u8003https://blog.csdn.net/harris135/article/details/77879148?locationNum=3&fp